website_app/models.py
from sqlalchemy.sql import func
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
DB_NAME = "database.db"


class PyTweet(db.Model):
    __tablename__ = 'py_tweets'
    id = db.Column(db.Integer, primary_key=True)
    tweet_text = db.Column(db.String(200), nullable=False)
    date = db.Column(db.DateTime, default=func.now())
    username = db.Column(db.String(100), nullable=False)


class FlTweet(db.Model):
    __tablename__ = 'fl_tweets'
    id = db.Column(db.Integer, primary_key=True)
    tweet_text = db.Column(db.String(200), nullable=False)
    date = db.Column(db.DateTime, default=func.now())
    username = db.Column(db.String(100), nullable=False)

website_app/__init__.py
from flask import Flask
from .views import views
from flask_sqlalchemy import SQLAlchemy
from config import SECRET_KEY
import math
from os import path
from .models import PyTweet, FlTweet, db, DB_NAME

def create_app():
    app = Flask(__name__, template_folder="templates")
    app.register_blueprint(views, url_prefix='/')
    app.config['SECRET_KEY'] = SECRET_KEY
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    create_database(app)

    @app.template_filter('ceil')
    def ceil_filter(value):
        return math.ceil(value)

    @app.template_filter('length')
    def length_filter(arr: list):
        return len(arr)

    return app


def create_database(app):
    if not path.exists('instance/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print('Created Database!')

website_app/views.py
from flask import Blueprint, render_template, url_for, request, redirect, session
from datetime import date
import math
import os
from config import ITEMS_PER_PAGE, ADMIN_PASSWORD
from .models import PyTweet, FlTweet, db

views = Blueprint('views', __name__)


@views.route("/")
def index():
    return render_template("index.html")


@views.route("/python")
def python_index():
    page = request.args.get('page', default=1, type=int)

    offset = (page - 1) * ITEMS_PER_PAGE

    # Database query with an offset and a limit
    tweets = PyTweet.query.order_by(PyTweet.date.desc()).offset(offset).limit(ITEMS_PER_PAGE).all()
    total_pages_amount = 1 if PyTweet.query.count() == 0 else math.ceil(PyTweet.query.count() / 6)

    return render_template("python.html", tweets=tweets, pg=page, total_pg=total_pages_amount)


@views.route("/flask")
def flask_index():
    page = request.args.get('page', default=1, type=int)

    offset = (page - 1) * ITEMS_PER_PAGE

    # Database query with an offset and a limit
    tweets = FlTweet.query.order_by(FlTweet.date.desc()).offset(offset).limit(ITEMS_PER_PAGE).all()
    total_pages_amount = 1 if FlTweet.query.count() == 0 else math.ceil(FlTweet.query.count() / 6)

    return render_template("flask.html", tweets=tweets, pg=page, total_pg=total_pages_amount)


@views.route("/learn")
def learn_index():
    return render_template("learn.html")


@views.route('/admin_panel')
def admin_panel():
    if session.get('logged_in'):
        view_all = request.args.get('view_all', default='False') == 'True'
        error_message = request.args.get('error_message', 'False') == 'True'
        len_py_tweets = PyTweet.query.count()
        len_fl_tweets = FlTweet.query.count()

        if len_py_tweets >= 3 and not view_all:
            py_tweets = PyTweet.query.order_by(PyTweet.date.desc()).limit(3).all()
        else:
            py_tweets = PyTweet.query.order_by(PyTweet.date.desc()).all()

        if len_fl_tweets >= 3 and not view_all:
            fl_tweets = FlTweet.query.order_by(FlTweet.date.desc()).limit(3).all()
        else:
            fl_tweets = FlTweet.query.order_by(FlTweet.date.desc()).all()

        return render_template('admin_panel.html', py_tweets=py_tweets, fl_tweets=fl_tweets,
                                view_all=view_all, error_message=error_message, py_len=len_py_tweets, fl_len=len_fl_tweets)

    else:
        return redirect(url_for('views.signin'))


@views.route('/error')
def error():
    return render_template('error.html')


@views.route("/python/write_tweet/<int:page_num>", methods=["POST"])
def python_write_tweet(page_num):
    new_tweet = PyTweet(tweet_text=request.form['tweet'], username=request.form['username'])
    db.session.add(new_tweet)
    db.session.commit()
    return redirect(url_for('views.python_index', page=page_num))


@views.route("/flask/write_tweet/<int:page_num>", methods=["POST"])
def flask_write_tweet(page_num):
    new_tweet = FlTweet(tweet_text=request.form['tweet'], username=request.form['username'])
    db.session.add(new_tweet)
    db.session.commit()
    return redirect(url_for('views.flask_index', page=page_num))


@views.route("/signin", methods=["GET", "POST"])
def signin():
    if request.method == "GET":
        return render_template("signin.html", error_message=False)
    else:
        if request.form["password"] == ADMIN_PASSWORD:
            session['logged_in'] = True
            return redirect(url_for('views.admin_panel'))
        else:
            return render_template("signin.html", error_message=True)


@views.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('views.index'))


@views.route("/search", methods=["GET"])
def search():
    keyword = (request.args.get("search-input")).lower()
    searched_tweets = []

    # I used SQLAlchemy queries with ilike for case-insensitive search in the database
    py_searched_tweets = PyTweet.query.filter(
        (PyTweet.tweet_text.ilike(f"%{keyword}%")) |
        (PyTweet.date.ilike(f"%{keyword}%")) |
        (PyTweet.username.ilike(f"%{keyword}%"))
    ).all()

    fl_searched_tweets = FlTweet.query.filter(
        (FlTweet.tweet_text.ilike(f"%{keyword}%")) |
        (FlTweet.date.ilike(f"%{keyword}%")) |
        (FlTweet.username.ilike(f"%{keyword}%"))
    ).all()

    searched_tweets = py_searched_tweets + fl_searched_tweets
    error_message = True if not searched_tweets else False

    return render_template("searched_tweets.html", error_message=error_message, tweets=searched_tweets)


@views.route('/delete_tweet/<forum>/<int:tweet_id>', methods=["GET", "POST"])
def delete_tweet(forum, tweet_id):
    error_message = False
    if forum == "python":
        tweet_to_delete = PyTweet.query.get(tweet_id)
        if tweet_to_delete:
            db.session.delete(tweet_to_delete)
            db.session.commit()
            return redirect(url_for('views.admin_panel', view_all=True))
        else:
            return "Tweet not found", 404

    else:
        tweet_to_delete = FlTweet.query.get(tweet_id)
        if tweet_to_delete:
            db.session.delete(tweet_to_delete)
            db.session.commit()
            return redirect(url_for('views.admin_panel', view_all=True))
        else:
            return "Tweet not found", 404


website_app/templates/admin_panel.html
{% extends "base.html" %}
{% block title %} Admin panel {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_admin.css') }}"> {% endblock %}

{% block content %}
<section class="main">
<div class="admin-panel">
    <div class="home-btn-container">
        <a href="{{ url_for('views.logout') }}">
            <button class="home-btn">Leave</button>
        </a>
    </div>
    <h1 class="admin-title">Welcome to Admin Panel</h1>

    <form class="search" action="{{ url_for('views.search')}}" method="get">
        <input type="text" name="search-input" placeholder="Enter a keyword" required>
        <button type="submit" class="search-btn">Search</button>
    </form>

    {% if error_message == True %}
    <div class="error-message">
        <p>Can't delete any more tweets on this forum!</p>
    </div>
    {% endif %}

    <div class="tweets-container">
        <div class="python_tweets">
            <div class="column-title">
            <h2>Python Forum Tweets</h2>
            </div>
            {% for i in range(py_tweets | length) %}
            <div class="tweet">
                <div class="tweet-info">
                    <p class="username">{{ py_tweets[i]['username'] }}</p>
                    <p class="date">{{ py_tweets[i]['date'] }}</p>
                </div>
                <p class="tweet-text">{{ py_tweets[i]['tweet_text'] }}</p>
                 <form action="{{ url_for('views.delete_tweet', forum='python', tweet_id=py_tweets[i]['id']) }}" method="get">
                    <button class="delete-btn" type="submit">Delete</button>
                 </form>
            </form>
            </div>
            {% endfor %}
        </div>
        <div class="flask_tweets">
            <div class="column-title">
            <h2>Flask Forum Tweets</h2>
            </div>
            {% for i in range(fl_tweets | length) %}
            <div class="tweet">
                <div class="tweet-info">
                    <p class="username">{{ fl_tweets[i]['username'] }}</p>
                    <p class="date">{{ fl_tweets[i]['date'] }}</p>
                </div>
                <p class="tweet-text">{{ fl_tweets[i]['tweet_text'] }}</p>
                <form action="{{ url_for('views.delete_tweet', forum='flask', tweet_id=fl_tweets[i]['id']) }}" method="get">
                    <button class="delete-btn" type="submit">Delete</button>
                 </form>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if py_len > 3 or fl_len > 3 %}
        {% if view_all == True %}
        <a href="{{ url_for('views.admin_panel', view_all=False) }}">
            <button class="view-all-btn">Hide</button>
        </a>
        {% else %}
         <a href="{{ url_for('views.admin_panel', view_all=True) }}">
            <button class="view-all-btn">View all</button>
        </a>
        {% endif %}
    {% endif %}
</div>
</section>
{% endblock %}

website_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Default value {% endblock %}</title>
    {% block style %}<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">{% endblock %}
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

website_app/templates/error.html
{% extends "base.html" %}
{% block title %} Not found {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_error.css') }}"> {% endblock %}

{% block content %}
<section class="main">
<div class="panel">
    <div class="back-btn-container">
        <a href="{{ url_for('views.index') }}">
            <button class="back-btn">Home</button>
        </a>
    </div>
    <h2 class="error-message">Oops! Something went wrong.</h2>
</div>
</section>
{% endblock %}

website_app/templates/flask.html
{% extends "base.html" %}
{% block title %} Flask forum {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_flask.css') }}"> {% endblock %}

{% block content %}
<header>
    <nav class="navbar">
        <ul>
            <a href="{{ url_for('views.index') }}"><li>Home</li></a>
            <a href="{{ url_for('views.python_index') }}"><li>Python</li></a>
            <a href="{{ url_for('views.flask_index') }}"><li>Flask</li></a>
            <a href="{{ url_for('views.learn_index') }}"><li>Learn</li></a>
        </ul>
        <a href="{{ url_for('views.signin') }}">
            <button>Sign in</button>
        </a>
    </nav>
</header>
<section class="main">
    <style>
    .main {
        background: linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.3)), url("{{ url_for('static', filename='images/flask_background.jpg') }}");
        background-size: cover;
        background-position: center center;
      }
    </style>
    <h1><span style="color:rgb(11, 255, 190); font-style:italic">Flask</span> discussion forum</h1>
    <div class = "tweetboard">
        <div class="tweets-title">
            <a href="{% if pg == 1 %}{{ url_for('views.flask_index', page=total_pg) }}{% else %}{{ url_for('views.flask_index', page=pg-1) }}{% endif %}">< Prev page</a>
            <h2>Tweets (page {{ pg }}/{{ total_pg }})</h2>
            <a href="{% if pg == total_pg %}{{ url_for('views.flask_index', page=1) }}{% else %}{{ url_for('views.flask_index', page=pg+1) }}{% endif %}">Next page ></a>
        </div>
        <hr>
        <div class="write-tweet-title">
            <p>Username</p>
            <p>Tweet text</p>
        </div>
        <form class="write-tweet" action="{{ url_for('views.flask_write_tweet', page_num=pg) }}" method="post">
            <input class="username-input" type="text" name="username" maxlength="40">
            <input class="tweet-input" type="text" name="tweet" maxlength="80">
            <button type="submit">Write a tweet</button>
        </form>
        <hr>

        <div class = "tweets">
            {% for i in range(tweets | length) %}
            <div class = "tweet">
                <div class="tweet-info">
                <p class="username">@{{ tweets[i]['username'] }}</p>
                <p class="date">{{ tweets[i]['date'] }}</p>
                </div>
                <p class="tweet-text">{{ tweets[i]['tweet_text'] }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

website_app/templates/index.html
{% extends "base.html" %}
{% block title %} Home page {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"> {% endblock %}

{% block content %}
<header>
    <nav class="navbar">
        <ul>
            <a href="{{ url_for('views.index') }}"><li>Home</li></a>
            <a href="{{ url_for('views.python_index') }}"><li>Python</li></a>
            <a href="{{ url_for('views.flask_index') }}"><li>Flask</li></a>
            <a href="{{ url_for('views.learn_index') }}"><li>Learn</li></a>
        </ul>
        <a href="{{ url_for('views.signin') }}">
            <button>Sign in</button>
        </a>
    </nav>
</header>
<section class="main">
    <style>
      .main {
        background: linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4)), url("{{ url_for('static', filename='images/main.jpg') }}");
        background-position: center center;
        background-size: cover;
      }
    </style>
    <div class="title">
        <h1>Welcome to PyFlask!</h1>
        <p>Here you can ask any questions about <span style="color:#00fffb; font-weight:bold;">Python</span> and <span style="color:rgb(18, 240, 166); font-weight:bold;">Flask</span></p>
    </div>
    <div class="pick-title"><h3>Pick a forum</h3></div>
    <div class ="forums">
        <div class="python-forum">
            <img src="{{ url_for('static', filename='images/python_forum.jpeg') }}" alt="Python image (cool)"/>
            <a href="{{ url_for('views.python_index') }}">
                <div class="layer1">
                    <h2>Python</h2>
                </div>
            </a>
        </div>
        <div class="flask-forum">
            <img src="{{ url_for('static', filename='images/flask_forum.jpeg') }}" alt="Flask image (cool)"/>
            <a href="{{ url_for('views.flask_index') }}">
                <div class="layer2">
                    <h2>Flask</h2>
                </div>
            </a>
        </div>
    </div>
</section>
{% endblock %}

website_app/templates/learn.html
{% extends "base.html" %}
{% block title %} Learn {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_learn.css') }}"> {% endblock %}

{% block content %}
    <header>
        <nav class="navbar">
            <ul>
                <a href="{{ url_for('views.index') }}"><li>Home</li></a>
                <a href="{{ url_for('views.index') }}"><li>Python</li></a>
                <a href="{{ url_for('views.flask_index') }}"><li>Flask</li></a>
                <a href="{{ url_for('views.learn_index') }}"><li>Learn</li></a>
            </ul>
            <a href="{{ url_for('views.signin') }}">
                <button>Sign in</button>
            </a>
        </nav>
    </header>
    <section class="main">
        <style>
          .main {
            background: linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.4)), url("{{ url_for('static', filename='images/main.jpg') }}");
            background-position: center center;
            background-size: cover;
          }
        </style>
        <div class = "python-board">
            <div class="python-image">
                <img src="{{ url_for('static', filename='images/python_forum.jpeg') }}" alt="Python image (cool)"/>
                <a href="{{ url_for('views.python_index') }}">
                    <div class="layer1">
                        <h2>Visit Forum</h2>
                    </div>
                </a>
            </div>
            <div class="python-text">
                <h1>Python</h1>
                <p>Python is a simple, versatile programming language used in web development, data science, automation, and more. 
                    Its readable syntax and strong library support make it ideal for both beginners and professionals.</p>
            </div>
        </div>
        <div class = "flask-board">
            <div class="flask-image">
                <img src="{{ url_for('static', filename='images/flask_forum.jpeg') }}" alt="Flask image (cool)"/>
                <a href="{{ url_for('views.flask_index') }}">
                    <div class="layer2">
                        <h2>Visit Forum</h2>
                    </div>
                </a>
            </div>
            <div class="flask-text">
                <h1>Flask</h1>
                <p>Flask is a lightweight Python web framework that is easy to use and highly flexible. 
                    It offers essential tools to build web applications and can scale for larger projects with the help of extensions.</p>
            </div>
        </div>
    </section>

{% endblock %}

website_app/templates/python.html
{% extends "base.html" %}
{% block title %} Python forum {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_python.css') }}"> {% endblock %}

{% block content %}
<header>
    <nav class="navbar">
        <ul>
            <a href="{{ url_for('views.index') }}"><li>Home</li></a>
            <a href="{{ url_for('views.python_index') }}"><li>Python</li></a>
            <a href="{{ url_for('views.flask_index') }}"><li>Flask</li></a>
            <a href="{{ url_for('views.learn_index') }}"><li>Learn</li></a>
        </ul>
        <a href="{{ url_for('views.signin') }}">
            <button>Sign in</button>
        </a>
    </nav>
</header>
<section class="main">
    <style>
    .main {
        background: linear-gradient(to bottom, rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.5)), url("{{ url_for('static', filename='images/python_background.jpg') }}");
        background-size: cover;
        background-position: center center;
      }
    </style>
    <h1><span style="color:#00fffb; font-style:italic">Python</span> discussion forum</h1>
    <div class = "tweetboard">
        <div class="tweets-title">
            <a href="{% if pg == 1 %}{{ url_for('views.python_index', page=total_pg) }}{% else %}{{ url_for('views.python_index', page=pg-1) }}{% endif %}">< Prev page</a>
            <h2>Tweets (page {{ pg }}/{{ total_pg }})</h2>
            <a href="{% if pg == total_pg %}{{ url_for('views.python_index', page=1) }}{% else %}{{ url_for('views.python_index', page=pg+1) }}{% endif %}">Next page ></a>
        </div>
        <hr>
        <div class="write-tweet-title">
            <p>Username</p>
            <p>Tweet text</p>
        </div>
        <form class="write-tweet" action="{{ url_for('views.python_write_tweet', page_num=pg) }}" method="post">
            <input class="username-input" type="text" name="username" maxlength="40">
            <input class="tweet-input" type="text" name="tweet" maxlength="80">
            <button type="submit">Write a tweet</button>
        </form>
        <hr>

        <div class = "tweets">
            {% for i in range(tweets | length) %}
            <div class = "tweet">
                <div class="tweet-info">
                <p class="username">@{{ tweets[i]['username'] }}</p>
                <p class="date">{{ tweets[i]['date'] }}</p>
                </div>
                <p class="tweet-text">{{ tweets[i]['tweet_text'] }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

website_app/templates/searched_tweets.html
{% extends "base.html" %}
{% block title %} Admin panel {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_searched_tweets.css') }}"> {% endblock %}

{% block content %}
<section class="main">
<div class="panel">
    <div class="back-btn-container">
        <a href="{{ url_for('views.admin_panel') }}">
            <button class="back-btn">Back</button>
        </a>
    </div>
    {% if error_message %}
    <h2 class="error-message">Error! No tweets found</h2>
    {% else %}
    <h1 class="title">Found tweets</h1>
    <div class="tweets">
        {% for i in range(tweets|length) %}
        <div class="tweet">
            <div class="tweet-info">
                <p class="username">{{ tweets[i]['username'] }}</p>
                <p class="date">{{ tweets[i]['date'] }}</p>
            </div>
            <p class="tweet-text">{{ tweets[i]['tweet_text'] }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
</section>
{% endblock %}

website_app/templates/signin.html
{% extends "base.html" %}
{% block title %} Sign in {% endblock %}
{% block style %} <link rel="stylesheet" href="{{ url_for('static', filename='css/style_signin.css') }}"> {% endblock %}

{% block content %}
<div class="signin-container">
    <form action="{{ url_for('views.signin') }}" method="post" class="signin-form">
        <h2>Sign into Admin Panel</h2>
        <input type="password" name="password" placeholder="Enter password" required>
        <button type="submit">Sign In</button>
    </form>

    {% if error_message == True %}
    <div class="error-message">
        <h3>Wrong password!</h3>
        <p>Enter the correct password or leave this page if you are not the admin.</p>
    </div>
    {% endif %}

    <a href="{{ url_for('views.index') }}" class="home-btn">Return to Home</a>
</div>

{% endblock %}